== Configuration

=== Settings

==== Time settings

===== Default time allowance per day

This setting determines the total number of minutes a user will have for the day by default.

TIP: The value of *Default time allowance per day* should be a whole number.

===== Default time allowance per session

This setting determines the total number of minutes a user will have for each _session_ per day. So, if a system is configured with 120 minutes time allowance per day, and 30 minutes time allowance per sessions, a user will be able to log in 4 times per day for 30 minutes at a time.

TIP: The value of *Default time allowance per session* should be a whole number.

===== Default guest time allowance per day

This is the same as *Default time allowance per day*, except for guest accounts instead of regular users.

TIP: The value of *Default time allowance per day* should be a whole number.

===== Default guest time allowance per session

This is the same as *Default time allowance per session*, except for guest accounts instead of regular users.

TIP: The value of *Default guest time allowance per day* should be a whole number.

==== Automatic time extension

Libki has an automatic time extension system that allows users to remain logged into a client computer beyond the pre-determined number of minutes per session a user is allotted.

===== Extension length

The amount of time to automatically increase a user's session time by \( in minutes \).

TIP: The value of *Extension length* should be a whole number.

===== Extend time at

This setting controls at what point in time an extension length is triggered. A session will be extended when the user's session time drops below this number, in minutes.

TIP: The value of *Extend time at* should be a whole number.

===== Extend time unless

This setting determines if a user is eligible for an automatic time extension. It has two options:

* User's client is reserved
** This choice prevents a time extension in the case that the user's client is reserved. Reservations for other client's are not taken into account.
* Any client is reserved
** This choice prevents a time extension in the case that *any* client is currently reserved. If any client is reserved a time extension will not take place, even if the users's client is not currently reserved,

===== When extending time

This setting determines how minutes are added to a patron's account when an automatic time extension occurs. It has two options:

* Take minutes from daily allotment
** This options moves minutes from the user's daily allotment of minutes to the user's session minutes. That means the user can continue using the client computer, but only up to his or her daily allotment of time.
* Don't take minutes from daily allotment
** This option adds minutes to a users session "out of thin air". As such, it does not effect how many sessions a user will have per day.

==== Client behavior

===== Client reservations

This setting controls how clients may be used by users. There are three possibilities.

* First come, first served.
** Allows a patron to log in to any client not currently being used.
* Reservation only.
** Requires a patron to place a reservation for a client before logging in to it.
* First come first served, with option to place reservation.
** A hybrid approach that allows patrons to log in to any client that is not currently in use or reserved.

TIP: The setting Display usernames controls if the user's username is displayed on the reserved client computer.

===== Client inactivity

These settings control the default automatic logout due to user inactivity.

TIP: These server settings can be overridden on a per-client basis. See the <<desktop-client.adoc#client-inactivity,Client configuration>> for more details.

====== Client inactivity warning

Warn user that they will be logged out automatically after this many minutes of inactivity.

====== Client inactivity logout

Log user out automatically after this many minutes of inactivity.

====== Client registration update delay limit

When a Libki client launches, it periodically connects to the Libki server to register itself. If a client does not re-register itself within this number of minutes, the Libki server will remove it from the list of active clients.

TIP: The value of *Client registration update delay limit* should be a whole number.

===== Client login banners

The client banners are optional areas on the top and bottom of the Libki client login screen. They are functionally like to web browsers. As such, anything that is viewable in a web browser is viewable in the banner areas \( size permitting \).

===== Source URL

The URL for the image or html that you wish to display in the banner section.

===== Width

If the *Source URL* is an image, it can be forced to a specific width instead of using the image's actual width. Leave empty to use the image's actual width.

===== Height

This is the same as *Width* for the *Source URL* but for height.

==== Client power options

===== Client power off settings

====== Power off action

Choose whether the "turn off" button and "automatic shutdown" function cause the clients to shutdown completely or be put in a suspend state.

TIP: Note that some setups won't permit the use of the wake on LAN fonctionnality together with the shutdown option. Suspend must be chosen in this case.

====== Client automatic shutdown delay

Libki can automatically send a power off signal to the clients after closing time. Use this setting to control how many minutes after closing this is done. Leave empty to disable.

===== Client power on settings

Libki uses wake on LAN to power on the clients. The machines must be wake on LAN capable and it must be enabled. This might require some configuration in the operating system and/or BIOS settings of the machine.

====== Send the signal using

By default, the wake on LAN packet is sent by the server. It is possible to configure the setup to use a running Libki client to send the packet to wake up the other machines.

TIP: This can be used to wake machines on another network without having to contact a public address on the clients' side.

====== Host

This setting is optionnal. If left empty, the limited broadcast address (255.255.255.255) is used. This should be enough when the server is in the same local network as the clients.

To target another node or a distant network, specify the IP address or fully qualified domain name (FQDN).

TIP: It is possible to use wake on LAN over the internet, by forwarding requests to the local broadcast address either via port forwarding at the router level or a forwarding service running on a dedicated machine.

====== Port

The port number for the magic packet. This setting is optionnal and defaults to the discard service (9).

====== MAC addresses

This is the list of the physical addresses of the network adapters used to wake the machines.

TIP: The format is one address per line, where each address uses either no separator or *:*.

======= Automatic power on time

Libki can automatically send a wake up signal to each machine whose MAC address is listed in the *MAC addresses* setting. All the machines will be woken up at this time each day. Leave empty to disable.

==== Custom Javascript

===== Administration interface JavaScript

Add custom JavaScript for the admin interface in this text box.

===== Public interface JavaScript

Add custom JavaScript for the public interface in this text box.

==== Data retention

===== History anonymization

This setting controls how long user and client data is retained in an un-anonymized format. If this setting is left empty, the data will be kept indefinitely.

When anonymized, a particular user will be given a new random id on a per-day basis. In this way, statistics will still be able to track usage on a per-user basis per day, but will be unable to track per-user usage over any longer time period.

TIP: The value of *History anonymization* should a whole number.

===== History retention

This setting controls how long user and client data is retained for the purpose of generating statistics and checking usage history, in days. If this setting is left empty, the data will be kept indefinitely.

TIP: The value of *History retention* should a whole number.

===== Inactive user retention

This setting controls how long a user can be inactive before being automatically deleted, in days. If this setting is left empty, all users will be kept indefinitely.

TIP: The value of *Inactive user retention* should be a whole number.

This setting should be used to conform to https://www.eugdpr.org/[GDPR] if necessary.

==== Guest passes

===== Prefix for guest passes

The phrase that each guest pass username should start with. If left empty, the phrase "guest" will be used (  e.g. guest1, guest2, guest3, etc ).

TIP: This setting can be a word or short phrase, but should contain only letters and numbers. Avoid using spaces or special characters.

===== Passes to create per batch

If the _Multiple guests_ button is used, this setting will control how many guest accounts are generated with each clock.

TIP: The value of *Passes to create per batch* should be a whole number.

===== Username label

The text in this field will be prepended to the guest username, ( e.g. _"Username:"_ ).

===== Password label

This setting works the same as *Username label* but for the generated password instead of the username.

===== Guest pass CSS

This setting allows the batch guest passes to be styled with CSS.
The default value for this setting is:
[source,css]
----
body { /* default body style emulates a pre tag */
    font-family: monospace;
    white-space: pre;
    display: block;
    unicode-bidi: embed;
}
.guest-pass { /* each username and password is in a guest-pass span */
    /* page-break-before: always; */ /* This will cause each pass to have a page break, good for use with receipt printers */
}
.guest-pass-username {} /* span containing the username label and the username itself */
.guest-pass-username-label {} /* span containing the username label */
.guest-pass-username-content {} /* span containing the username itself */
.guest-pass-password {} /* span containing the password label and the password itself */
.guest-pass-password-label {} /* span containing the password label */
.guest-pass-password-content {} /* span containing the password itself */
----

==== ILS integration

===== Patron hyperlinks

Entering a url here will cause the username in the user's table of the web administration to become a hyperlink with the user's username at the end. For example, _http://catalog.koha.library/cgi-bin/koha/members/member.pl?quicksearch=1&searchmember=_ will link to the Koha ILS's search function for the given username.

===== SIP configuration

Single Sign-on can with an ILS can be achieved via SIP2. Settings for the ILS SIP2 server can be stored in the _libki\_local.conf_ file or the *SIP configuration* setting.

To enable SIP authentication, you will need to edit your libki_local.conf and add a section like this:
----
<SIP>
    enable 1
    host ils.mylibrary.org
    port 6001
    location LIB
    username libki_sipuser
    password PassW0rd
    terminator CR
    require_sip_auth 0
    enable_split_messages 0
    no_password_check 0 # <1>
    fee_limit 5.00 # <2>
    deny_on charge_privileges_denied # <3>
    deny_on recall_privileges_denied # <4>
    deny_on excessive_outstanding_fines # <5>
    deny_on_field AB:This is the reason we are denying you # <6>
    category_field PC # <7>
    pattern_personal_name , # <8>
</SIP>
----
<1> If enabled, Libki won't validate the password given against the SIP server, any password will work
<2> Can be either a fee amount, or a SIP2 field that defines the fee limit ( e.g. CC ), delete for no fee limit
<3> You can set SIP2 patron status flags which will deny patrons the ability to log in
<4> You can set as many or as few as you want. Delete these if you don't want to deny patrons.
<5> The full listing is defined in the SIP2 protocol specification
<6> You can require arbitrary SIP fields to have a value of Y for patrons to be allowed to log in. The format of the setting is _<Field>:<Message>_.
<7> Specify a SIP tag here that contains the user category in the SIP user lookup response
<8> Specify a pattern for splitting lastname and firstname in personal name field(AE) in SIP response

An equivilent configuration set via YAML in the system settings would look like this:
[source,yaml]
----
enable: 1
host: ils.mylibrary.org
port: 6001
location: LIB
username: libki_sipuser
password: PassW0rd
terminator: CR
require_sip_auth: 0
enable_split_messages: 0
fee_limit: 5.00
deny_on:
  - charge_privileges_denied
  - recall_privileges_denied
  - excessive_outstanding_fines
deny_on_field: "AB:This is the reason we are denying you"
category_field: PC
pattern_personal_name: ","
----

The SIP section requires the following parameters:

* enable: Set to 1 to enable SIP auth, 0 to disable it.
* host: The SIP server's IP or FQDN.
* port: The port that SIP server listens on.
* location: The SIP location code that matches the sip login.
* username: The username for the SIP account to use for transactions.
* password: The password for the SIP accouant to use for transactions.
* terminator: This is either CR or CRLF depending on the SIP server. Default is CR
* require_sip_auth: Does this SIP server require a message 93 login before it can be used? If so this should be set to 1 and the username/password fields should be populated. This should be set to 1 for Koha.
* enable_split_message: IF thie server supports split messages you can enable this. This should be set to 0 for Koha.
* fee_limit: As notated, this can be a set number or a SIP field to check. If the fee limit is exceeded, the user login will be denied.
* deny_on: This can be repeated to deny logins based on the patron information flags detailed in the SIP2 protocol specification.
* deny_on_field: This can be repeated to deny logins if the Specified field does not have a value of "Y".
==== LDAP

Single Sign-on with other systems can be achieved via LDAP. Settings for LDAP server are currently stored in the _libki\_local.conf_ only, though setting support is expected soon.

TIP: Make sure the URL beings with http:// or https:// as necessary.

==== Print management

===== Printer configuration

Refer to the main Print Management section for details.

==== Reservations

===== Reservation timeout

The amount of time \( in minutes \) that a user has to log into his or her reserved computer. If the user does not log in within the specified time limit, the reserved client will become available again.

TIP: The value of *Reservation timeout* should be a whole number.

===== Display usernames

This setting determines if a Libki client that is reserved and waiting will display the username of the person it is waiting for.

==== Terms of service

This setting allows a library to add _terms of service_ for use of computers running the Libki client. Simply adding text of your terms of service in the textbox will cause the terms to be displayed to any person logging into a Libki client. If the person chooses _yes_ the login will proceed as usual. If the person chooses _no_ the login screen will be reset.

==== User settings

===== User categories

Add your list of user categories here as a list in YAML syntax.

Example:
[source,yaml]
----
---
- 'Category 1'
- 'Category 2'
- 'Category 3'
----

If Single Sign-on via SIP integration has been set up, and the SIP configuration for `category_field` has been set up, values from the SIP field will be automatically added to this list as the appear for the first time via SIP.

==== Advanced settings

===== Advanced rules

In this section, advanced rules can be set up to deterimine a number of behaviors based on various criteria.

For example:
[source,yaml]
----
-
  criteria:
    user_category: MyCategory1
    client_location: MyLocation1
  rules:
    session: 25
    guest_session: 20
-
  criteria:
    client_location: MyLocation1
  rules:
    session: 20
    guest_session: 20
-
  criteria:
    user_category: MyCategory1
  rules:
    session: 15
    guest_session: 20
-
  rules:
    session: 10
    guest_session: 20
----

Rules should be list from most specific to least specific.
If a criteria is missing in a rule, then it is not used as part if the matching process.

For example, let's say we are attempting to log in as a patron with the category `MyCategory1`, and a client with the location `MyLocation2`.

* The first rule matches category, but not location, so it is skipped.
* The second rule only checks location, which is not a match, so it is skipped.
* The third rule only checks category, which matches, so it is used!
* The last rule has no critea, so it matches on *everything*

If there is no catch-all rule like this, Libki will fall back to the default time allowance settings from the `Time settings` section.

====== Even if a rule should match, it will be skipped if it doesn't contain the 'subrule' we are looking for

For example, take the following:
[source,yaml]
----
-
  criteria:
    client_location: MyLocation1
  rules:
    session: 15
-
  rules:
    session: 10
    guest_session: 20
----

Assume a guest is logging in to a `MyLocation1` client.

* The first rule will be skipped because guest_session is not defined in this rule.
* The second rule will be used because it matches all and *does* have guest_session defined.

====== Rules can specify multiple values for a given criteria

For example:
[source,yaml]
----
-
  criteria:
    user_category:
      - MyCategory1
      - MyCategory2
    client_location: MyLocationA
  rules:
    session: 25
    daily: 50
    guest_session: 20
    guest_daily: 45
----

The above example would apply to any user of category `MyCategory1` *or* `MyCategory2` logging into a client at location `MyLocationA`.

That is, this rule will apply to all the values in the list for that criteria.

Another way to think of it is that all criteria are AND'ed, and all the values for a criteria are OR'ed.

[source,yaml]
----
-
  criteria:
    user_category:
      - Cat1
      - Cat2
    client_location:
      - LocA
      - LocB
  rules:
    session: 25
    daily: 50
    guest_session: 20
    guest_daily: 45
----

Would be expressed in SQL like:
`SELECT rule WHERE ( user_category = Cat1 OR user_category = Cat2 ) AND ( client_location = LocA OR client_location = LocB )`

====== Rule options

The list of all possible criteria include:

* `client_location`
* `client_name`
* `user_category`

The list of all possible rules include:

* `session`: The number of minutes per session a registered user is given
* `guest_session`: The number of minutes per session a guest user is given
* `daily`: The daily allotment of minutes to be given to a registered user for the day
* `guest_daily`: The daily allotment of minutes to be given to a guest user for the day
* `no_reservation_required`: Even if "Client reservations" is set to "Reservation only", allows a login without a reservation. The value should be '1' to enable.

=== Closing hours

Closing hours are a way to prevent users from starting a session that will be cut short by the closing of the location he or she is at. Closing hours can be set on a site-wide basis, or on a per-location basis. If a given location has no closing hours set, that location will use the _All locations_ closing hours.

=== Print management

Print management in Libki can be done using two different backends: Libki Print Manager or CUPS.

==== Configuring your server with Libki Print Manager

Install and configure Libki Print Manager on a computer that can print directly to your physical printers.

===== Setting up your print management configuration

Below is an example with 6 virtual printers, 1 each for monochrome and color variations of simplex, long duplex and short duplex.

[source,json]
----
---
printers:
  color:
    chroming: color
    physical_printer_name: somePrinter
    plexing: simplex
    type: PrintManager
  color-duplex-long:
    chroming: color
    physical_printer_name: somePrinter
    plexing: duplexlong
    type: PrintManager
  color-duplex-short:
    chroming: color
    physical_printer_name: somePrinter
    plexing: duplexshort
    type: PrintManager
  monochrome:
    chroming: monochrome
    physical_printer_name: somePrinter
    plexing: simplex
    type: PrintManager
  monochrome-duplex-long:
    chroming: monochrome
    physical_printer_name: somePrinter
    plexing: duplexlong
    type: PrintManager
  monochrome-duplex-short:
    chroming: monochrome
    physical_printer_name: somePrinter
    plexing: duplexshort
    type: PrintManager
----

==== Configuring your server with CUPS

To set up print management using CUPS, you need to know the name of the CUPS server (or its IP address), the username used to conect to that server and the name of the printer that will be set up.

===== Setting up your print management configuration

You can use the configuration below as a template, simply replace the `server` and `username` field values with your own.

[source,json]
----
cups:
      server: localhost
      username: print

printers:
  PDF:
    type: cups
    name: PDF
----

==== Configuring your clients

After you've set up your server for print management, you will then need to configure your clients as well.
To accomplish this, you must edit the `Libki Kiosk Management System.ini` file.
On Windows operating systems, this file is most often located in `C:\ProgramData\Libki` but may be located elsewhere depending on your specific OS configuration.
You will most likely need to edit this file as an Administrator.

Once you have located the file, you will need to add a new configuration block to the bottom.
```
[printers]
color="C:\\printers\\color"
monochrome="C:\\printers\\monochrome"
```

As you can see, the printers match the `name:` fields defined print management configuration for the server.
You will also need to ensure those directories exist on the client computer.
Once the Libki client has been started, it will watch those directories for PDF files.
When the client sees a file, it will uploaded it to the server with the matching printer name.

You can use any PDF print driver to print PDF file to these directories.
A custom PDF print driver for Libki is in development, but not yet available.
