== Configuration

=== Settings

==== Basics

===== Default time allowance per day

This setting determines the total number of minutes a user will have for the day by default.

TIP: The value of *Default time allowance per day* should be a whole number.

===== Default time allowance per session

This setting determines the total number of minutes a user will have for each _session_ per day. So, if a system is configured with 120 minutes time allowance per day, and 30 minutes time allowance per sessions, a user will be able to log in 4 times per day for 30 minutes at a time.

TIP: The value of *Default time allowance per session* should be a whole number.

===== Default guest time allowance per session

This is the same as *Default time allowance per session*, except for guest accounts instead of regular uses.

TIP: The value of *Default guest time allowance per session* should be a whole number.

===== Client registration update delay limit

When a Libki client launches, it periodically connects to the Libki server to register itself. If a client does not re-register itself within this number of minutes, the Libki server will remove it from the list of active clients.

TIP: The value of *Client registration update delay limit* should be a whole number.

==== Data retention

===== History retention

This setting controls how long user and client data is retained for the purpose of generating statistics and checking usage history, in days. If this setting is left empty, the data will be kept indefinitely.

TIP: The value of *History retention* should a whole number.

===== Inactive user retention

This setting controls how long a user can be inactive before being automatically deleted, in days. If this setting is left empty, all users will be kept indefinitely.

TIP: The value of *Inactive user retention* should be a whole number.

This setting should be used to conform to https://www.eugdpr.org/[GDPR] if necessary.

==== Client behavior

This setting controls how clients may be used by users. There are three possibilities.

* First come, first served.
** Allows a patron to log in to any client not currently being used.
* Reservation only.
** Requires a patron to place a reservation for a client before logging in to it.
* First come first served, with option to place reservation.
** A hybrid approach that allows patrons to log in to any client that is not currently in use or reserved.

TIP: The setting Display usernames controls if the user's username is displayed on the reserved client computer.

==== Reservations

===== Reservation timeout

The amount of time \( in minutes \) that a user has to log into his or her reserved computer. If the user does not log in within the specified time limit, the reserved client will become available again.

TIP: The value of *Reservation timeout* should be a whole number.

===== Display usernames

This setting determines if a Libki client that is reserved and waiting will display the username of the person it is waiting for.

==== Automatic time extension

Libki has an automatic time extension system that allows users to remain logged into a client computer beyond the pre-determined number of minutes per session a user is allotted.

===== Extension length

The amount of time to automatically increase a user's session time by \( in minutes \).

TIP: The value of *Extension length* should be a whole number.

===== Extend time at

This setting controls at what point in time an extension length is triggered. A session will be extended when the user's session time drops below this number, in minutes.

TIP: The value of *Extend time at* should be a whole number.

===== Extend time unless

This setting determines if a user is eligible for an automatic time extension. It has two options:

* User's client is reserved
** This choice prevents a time extension in the case that the user's client is reserved. Reservations for other client's are not taken into account.
* Any client is reserved
** This choice prevents a time extension in the case that *any* client is currently reserved. If any client is reserved a time extension will not take place, even if the users's client is not currently reserved,

===== When extending time

This setting determines how minutes are added to a patron's account when an automatic time extension occurs. It has two options:

* Take minutes from daily allotment
** This options moves minutes from the user's daily allotment of minutes to the user's session minutes. That means the user can continue using the client computer, but only up to his or her daily allotment of time.
* Don't take minutes from daily allotment
** This option adds minutes to a users session "out of thin air". As such, it does not effect how many sessions a user will have per day.

===== *Client login banner settings*

The client banners are optional areas on the top and bottom of the Libki client login screen. They are functionally like to web browsers. As such, anything that is viewable in a web browser is viewable in the banner areas \( size permitting \).

===== Source URL

The URL for the image or html that you wish to display in the banner section.

===== Width

If the *Source URL* is an image, it can be forced to a specific width instead of using the image's actual width. Leave empty to use the image's actual width.

===== Height

This is the same as *Width* for the *Source URL* but for height.

==== Guest passes

===== Prefix for guest passes

The phrase that each guest pass username should start with. If left empty, the phrase "guest" will be used \(  e.g. guest1, guest2, guest3, etc \).

TIP: This setting can be a word or short phrase, but should contain only letters and numbers. Avoid using spaces or special characters.

===== Passes to create per batch

If the _Multiple guests_ button is used, this setting will control how many guest accounts are generated with each clock.

TIP: The value of *Passes to create per batch* should be a whole number.

===== Username label

The text in this field will be prepended to the guest username, \( e.g. _"Username:"_ \).

===== Password label

This setting works the same as *Username label* but for the generated password instead of the username.

==== Third party integration

===== URL

Entering a url here will cause the username in the user's table of the web administration to become a hyperlink with the user's username at the end. For example, _http://catalog.koha.library/cgi-bin/koha/members/member.pl?quicksearch=1&searchmember=_ will link to the Koha ILS's search function for the given username.

TIP: Make sure the URL beings with http:// or https:// as necessary.

=== Closing Hours

Closing hours are a way to prevent users from starting a session that will be cut short by the closing of the location he or she is at. Closing hours can be set on a site-wide basis, or on a per-location basis. If a given location has no closing hours set, that location will use the _All locations_ closing hours.

=== Single Sign-on

==== SIP2

Single Sign-on can with an ILS can be achieved via SIP2. Settings for the ILS SIP2 server can be stored in the _libki\_local.conf_ file or the *SIP configuration* setting.

==== LDAP

Single Sign-on with other systems can be achieved via LDAP. Settings for LDAP server are currently stored in the _libki\_local.conf_ only, though setting support is expected soon.

=== Print Management

Print management in Libki is powered by Google Cloud Print. To set up print management, first set up your printers in Google Cloud Print. Next, generate a client id and secret. Finally, enter your configuration in the *Printer configuration* setting as YAML. The code block below is an example configuration with two printer profiles for a single printer ( one color, one monochrome ).

----
google_cloud_print:
  client_id: 893746288161-libc4aj9loitf5i2lcuuonj6ggqb37uc.apps.googleusercontent.com
  client_secret: dEjNmggj-PS9_LnvP92jIYu3

printers:
  color:
    type: google_cloud_print
    google_cloud_id: d4355eb9-5b5b-3982-1492-9a1245298409
    name: color
    ticket:
      color:
        type: STANDARD_MONOCHROME

  monochrome:
    type: google_cloud_print
    google_cloud_id: d4355eb9-5b5b-3982-1492-9a1245298409
    name: monochrome
    ticket:
      color:
        type: STANDARD_MONOCHROME
----
