== Contributing

=== Client & server

==== Submitting bug fixes and features

===== Formatting patches

* File an Issue on GitHub in the matching repository ( client, server, manual, etc... ) for the issue ( for both enhancement *and* bug fixes )
** The earlier you file the better. It's much better to file an issue stating your intention to develop a new feature or fix before you start to give other community members a chance to review the issue and give feedback.
* The subject line of your commit(s) should begin with "Issue XX: " followed by the description of what the patch does.
* Include a hyperlink to the GitHub issue this patch resolves.
** GitHub will notice and automatically link the commit to the issue.

===== Libki server

Pull requests for features and fixes to the Libki server should be submitting as pull requests via the https://github.com/Libki/libki-server[Libki server GitHub repository].

===== Libki client

Pull requests for features and fixes to the Libki client should be submitting as pull requests via the https://github.com/Libki/libki-client[Libki client GitHub repository].

==== Coding guidelines

===== Server coding guidelines

* Perltidy new or altered pieces of code before submission.
** Libki server comes with a .perltidyrc file that should always be used when tidying Libki server code.

[[contributing-manual]]
=== Manual

Suggestions for edits can be sent to the Libki Documentation Team as a merge request via GitHub.

To join the Libki Documentation Team, please contact Kyle Hall via the https://lists.sourceforge.net/lists/listinfo/libki-developers[Libki developers mailing list] or the https://libki.slack.com/[Libki Slack workspace].

The manual is currently available on https://github.com/Libki/libki-manual[GitHub].
