== Desktop client

=== Windows

==== Download

The Windows wizard installer for the Libki client can be downloaded from https://github.com/Libki/libki-client/releases

Make sure to download the client version that matches your Libki server version.

==== Installer wizard

After downloading the client, run it and you will be presented with the installer wizard.
Here you will be asked a series of questions about how you would like your client to be configured.

===== Scheme

Set this field to `https` if you have set up your Libki server behind an SSL-enabled proxy,
set it to `http` otherwise.

===== Host

Set this to the ip address or FQDN for your Libki server.

===== Port

Set this field to the external port your Libki server is listening on.

===== Location

Set this field to the location you wish to label this client as being at.
This is an arbitrary text field. If you are setting multiple clients to have the same location,
make sure that you use the exact same spelling for all the clients.

For example, you may set the location to `Main Floor` or `Children's Room`.

===== Run only for this user

If you enter a Windows account username in this field, the Libki client will only
launch when that Windows user is logged in to.

===== Run for all users but this one

This is the inverse of `Run only for this user`. If you set a Windows account username
in this field, the client will not run for that user, but will for all other users.

===== Client name

Here you can name this client node, each client should have a unique username otherwise
you will get unexpected behavior.

If you leave this field blank, Libki will user the client computers hostname as the Libki
client's name.

If you set the value of this field to `OS_USERNAME`, the logged in Windows account username
will be used as the client's name.

===== Logout action

This section will let you choose what happens when the Libki client logs out,
either because the patron's time has run out, or the patron chooses to log out early.

====== Reboot

This option will trigger a full reboot of the client PC.
This is useful when combined with the software http://www.faronics.com/products/deep-freeze/enterprise[Deep Freeze] or https://horizondatasys.com/reboot-restore-rx-freeware/[Reboot Restore Rx]
which resets the state of a computer each time it is rebooted.

====== Log out of operating system

This option will trigger a logout of the Windows account that the client is currently logged in as.
This is useful when combined with the software http://www.fortresgrand.com/products/cls/cls.htm[Clean Slate],
which resets the state of a computer each time that the Windows account is logged out.

====== Nothing

This option leaves the host OS in the state it is currently in, and merely redisplays the login screen.
This option is not recommended for production use. Any applications the user had open at the time the client
was logged off of will still be open.
This option is useful for testing and debugging.

===== Client disable password

Here you may enter a 'back door' password.
At any time, if this password is entered into the Libki login screen with an empty username, it will cause the Libki client to close.
This is useful in the event that a client loses connectivity with the server and is unable to verify logins.

===== Installation location

This is the path to which the Libki client will be installed.
It is recommended to use the default installation path unless you have a specific reason to do otherwise.

=== Linux

In order to use the libki client on Linux, you must compile it from source. This guide is written with Debian based distros in mind (like Debian, Ubuntu, Linux Mint or Elementary OS).

==== Compilation

Install required packages:

[source,bash]
----
sudo apt-get install git build-essential qtcreator qt5-default qttools5-dev-tools libqt5webkit5-dev libqt5script5 qtscript5-dev 
----

Download a copy of the libki client source.

[source,bash]
----
git clone https://github.com/libki/libki-client.git
----

* Open Qt Creator, then select *Open File or Project* from the file menu.
* Select the *Libki.pro* file in the source folder you just downloaded.
* Click *Configure project* and then select *Build Project Libki* from the build menu.

==== Installation

Copy the compiled client from the debug folder that was created. It's located in the same directory as the libki-client source folder. FIXME Lookup proper folder name!

[source,bash]
----
sudo cp libkiclient /usr/local/bin
----

Make it executable in case it for some reason isn't.

[source,bash]
----
sudo chmod +x /usr/local/bin/libkiclient
----

Copy the configuration file and edit it to your liking. See Configuration options below for additional information.

[source,bash]
----
nano ~/.config/Libki.ini
----

If the client is installed on another machine than the one compiling it, just some of the dependencies are needed.

[source,bash]
----
sudo apt-get install libqt5webkit5 libqt5script5
---- 

==== Configuration

===== Linux Mint with Cinnamon

====== Bypass prevention
https://github.com/Libki/libki-client/issues/39#issuecomment-562189590[Contributed] by https://github.com/loidor[Loidor]

I'm running libkiclient through startup applications without a delay, and that launches it fast enough.
Then I'm running a script I call demapper with a 2 second delay, because it isn't reliable with a shorter delay.
That disables Alt and Super, so it's impossible to switch workspace, launch the start menu and opening the run console.

Code for demapper:

[source,bash]
----
#!/bin/bash

xmodmap -e 'keycode 133='
xmodmap -e 'keycode 64='
----

Other bypass preventions:

* Disable the power button
* Disabling remote media popup (Nemo->Preferences->Behaviour)
* Replace the user shell with rbash chsh -s /bin/rbash USERNAME

I haven't encountered anyone terminal-savvy enough yet, but once I do I'll look into disabling kill, killall and pkill.

====== Autologin, backup, restore
I've disabled the screensaver, since I don't want the client to become locked, and have an autologin set in /etc/lightdm/lightdm.conf.

Together with this, I've got a backup/restore solution where backup copies /home/USERNAME to /opt/USERNAME. restore deletes /home/USERNAME and replaces it with /opt/USERNAME. Only root can run backup when needed (after changes), and restore is run on every logout through lightdm.conf.

backup code:
 
[source,bash]
----
#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

rm -rf /opt/public
cp -a /home/public /opt/public
echo "Backup klar."
----

restore code:

[source,bash]
----
#!/bin/bash

rsync -qrpog --delete --exclude '.X*' /opt/public /home/
echo "" > /home/public/.local/share/recently-used.xbel
rm /var/spool/cups/*
----

My lightdm.conf:

[source]
----
[Seat:*]
autologin-guest=false
autologin-user=public
autologin-user-timeout=5

session-cleanup-script=/usr/local/bin/restore
----

Other things:

* I install Google Chrome since pretty much everyone is familiar with it regardless of what system they're used to running. The keychain password is set to blank/unencrypted.
* I change LibreOffice Writer to save to docx as default.
* I add shortcuts to Chrome and Writer to the desktop.
* I remove terminal from the quick launch toolbar since most users don't know what it is.
* I remove logout and shutdown options from the start menu. (This is a PITA to do by hand, but here it goes:

In `/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js`, find the line `//Lock screen`.
Start a multiline comment there with +++`\*`+++ and go to the line `//Shutdown button`.
Somewhat close to that one, 15 lines or so, there should be a line saying `this.systemButtonsBox.add(button.aactor, { y_align: St.Align.END, y_fill: false });`.
End your multiline comment after this line with +++`*/`+++.

Finally, I set my preferred volume and remove the volume icon from the toolbar. All our clients have headphones, and they can leak quite a lot if the volume is high enough.

=== Configuration options

The Libki client may be customized further with options set in the configuration INI file that are not revealed in the installer wizard.

==== Labels

To modify the labels on the Libki login screen, you can set a `[label]` block. There valid options are:

* username
* password
* waiting_holds

You need only add lines to the `[label]` block for the labels you wish to modify. Any labels not redefined here will use the default word or words for
the given language in use.

```
[labels]
username="Username:"                        ; What text it will say at the username input field
password="Password:"                        ; What text it will say at the password input field
waiting_holds="You have holds waiting."     ; This can be used if your client connects to your library's ILS via SIP2.
```

==== Passwordless login

If you are using single-signon via SIP, and your SIP server is set to mark any password a users provides as valid, you can set the Libki client to passwordless mode.

To do so, simply add or modify the `no_passwords` key under the `[node]` section to appear like so:
```
no_passwords=1 ; Lets you hide the password field if passwords are not used.
```

==== Restrict client usage by age

It is possible to specify that a given Libki client can only be used by persons of a given age range.
To use this feature, just add a new key under the `[node]` section of the Libki client ini named `age_limit`.
This feature only works when using single-signon via SIP, and the SIP server returns a `PB` field of the date format `YYYYMMDD` where that date is the patron's date of birth.

Example:
```
[node]
age_limit="gt18"
```

This will limit the client to patrons older than 18. At the moment this only works via SIP2 as there is currently no way to edit a user's age from the staff administration.

Multiple age limits can be implemented delimited by commans, such as `age_limit="ge11,le17"` which will limit the client to users between ( and including ) the ages of 11 and 17.

The format first two characters are the comparison. Supported comparisons are:

* `eq`: equal to
* `ne`: not equal to
* `lt`: less than
* `gt`: greater than
* `le`: less than or equal to
* `ge`: greater than or equal to

It is possible to make a client unusable by anyone ( e.g. "gt18,lt17" ) so be careful with this configuration.

[[client-inactivity]]
==== Automatic logout due to inactivity

It is possible to configure the Libki client to log a patron out if no mouse movement has been detected in a given number of minutes. Additionaly, the user can be first warned after a different number of minutes. Both of these configurations exist as system settings on the Libki server.

It is also possibly to specifiy these configurations on a per-client basis, in the Libki client INI file. If these settings exist in the client INI file, they will override the settings from the server. In this way, the server settings can act as a default, with particular clients overriding those server provided settings.

Example:
```
[node]
inactivityLogout=5
inactivityWarning=3
```

In the above example, Libki will display an inactivity warning after 3 minutes with no mouse movement. The client will then log the user out after another 2 minutes of inactivity. If no warning is wanted, simply set inactivityWarning to a greater number than inactivityLogout.

==== Run external program on login
It is possible to configure the Libki client to launch another program when a user successfully logs into Libki.

Example:
```
[node]
run_on_login="C:\\Program Files\\Internet Explorer\\iexplore.exe"
```

In the above example, Libki will launch Internet Explorer after the patron has logged in successfully.



TIP: You can use single forward slashes instead of the double backslashes ( e.g. `C:/Program Files/Internet Explorer/iexplore.exe` )
