== Installation

=== One-step automatic install

Do you want to setup Libki as fast as possible and have a dedicated server? Then this is the choice for you. Just make sure your server is running Ubuntu 18.04 or Debian 10 (Buster) and that you don't have a user named 'libki'.

[source,bash]
----
wget -O- https://install.libki.org | sudo bash
----

(By the way, that's the letter O, not the number 0.)

=== Alternative method

Everyone doesn't want to pipe to bash. It prevents you from reading the code you're about to run on your system. If you want to read it through first, this alternative should be for you.

[source,bash]
----
git clone https://github.com/libki/libki-server.git
cd libki-server
sudo bash install.sh
----

=== Docker

The official Libki Server Docker image needs to be connected to a database server, it does not contain a MySQL instance within it.
Using a MySQL or a MariaDB container on the same Docker network is considered good practice.

The Libki Server image is available on https://hub.docker.com/r/libki/libki-server[Docker Hub].

This container requires some environment variables to be set in order to function correctly, the following is a mocked example of the environment variables needed:
----
LIBKI_INSTANCE=<INSTANCE> // <1>
LIBKI_DB_DSN=dbi:mysql:<DB_NAME>;host=<DB_HOSTNAME>;port=3306
LIBKI_DB_USER=<DB_USERNAME>
LIBKI_DB_PASSWORD=<DB_PASSWORD>
LIBKI_DB_HOST=<DB_HOSTNAME>
LIBKI_DB_PORT=3306
LIBKI_DB_DATABASE=<DB_NAME>
LIBKI_TZ=America/Denver // <2>
----
<1> Instance name, may be left empty for single-instance servers
<2> Find your timezome in the documentation https://metacpan.org/pod/DateTime::TimeZone::Catalog[here].

==== Cronjobs

The Libki cronjobs are not set to run inside the Docker container. Instead, it the cronjobs should be set up on the host machine.

Add the following to the root user's crontab or to a file in `/etc/cron.d/`.

```
* * * * * root docker exec <container-name> /app/script/cronjobs/libki.pl
0 0 * * * root docker exec <container-name> /app/script/cronjobs/libki_nightly.pl
```
