name: Update manual site
on: [push]
jobs:
  update-manual-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: libki-manual

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - run: mkdir -p output
      - run: docker pull asciidoctor/docker-asciidoctor
      - run: sed -i -e 's@##LIBKI_VERSION##@'"${{ steps.extract_branch.outputs.branch }}"'@g' libki-manual.adoc
      - run: sed -i -e 's@{libki-version}@'"${{ steps.extract_branch.outputs.branch }}"'@g' libki-manual.adoc
      - run: docker run -v $GITHUB_WORKSPACE/libki-manual:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output libki-manual.adoc
      - run: docker run -v $GITHUB_WORKSPACE/libki-manual:/documents/ --name asciidoc-to-pdf  asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output libki-manual.adoc
      - run: docker run -v $GITHUB_WORKSPACE/libki-manual:/documents/ --name asciidoc-to-epub asciidoctor/docker-asciidoctor asciidoctor-epub3 -D /documents/output libki-manual.adoc
      - run: git clone https://${GITHUB_TOKEN}@github.com/Libki/manual-libki-org.git
      - run: ls -alh
      - run: if [ -d "manual-libki-org/docs/${GITHUB_REF##*/}" ]; then rm -rf manual-libki-org/docs/${GITHUB_REF##*/}; fi
      - run: mkdir -p manual-libki-org/docs/${GITHUB_REF##*/}
      - run: cp -r libki-manual/output/. manual-libki-org/docs/${GITHUB_REF##*/}/.
      - run: cp -r libki-manual/images manual-libki-org/docs/${GITHUB_REF##*/}/.
      - run: cd manual-libki-org
      - run: ls -alh
      - run: git config user.name "Kyle M Hall"
      - run: git config user.email "kyle@bywatersolutions.com"
      - run: git add docs/${GITHUB_REF##*/}
      - run: git status
      - run: git commit -m "Deploy manual version '${GITHUB_REF##*/}' to libki.manual.org"
      - run: git push origin HEAD:master
